#!/usr/bin/env bash
# Bring up a Postgres instance for local development or tests.
#
# Tries Docker first (canonical path: the docker-compose.yml at repo root).
# Falls back to a system Postgres cluster (used in some ephemeral cloud envs
# where Docker is available but `docker compose` isn't, or where Postgres is
# already installed). On a developer machine with Docker, the fallback never
# fires.
#
# Output: prints the connection URL the rest of the project should use, and
# writes it to .env.local if one doesn't exist there yet.

set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

DB_NAME="${POSTGRES_DB:-tilbudstrolden}"
DB_USER="${POSTGRES_USER:-tilbudstrolden}"
DB_PASS="${POSTGRES_PASSWORD:-tilbudstrolden_dev}"
DB_PORT="${POSTGRES_PORT:-5432}"
DB_HOST="${POSTGRES_HOST:-127.0.0.1}"

DATABASE_URL=""

try_docker_compose() {
  if ! command -v docker >/dev/null 2>&1; then
    return 1
  fi
  if ! docker compose version >/dev/null 2>&1; then
    return 1
  fi
  # Fail fast if the daemon isn't reachable — avoids the 60s wait loop in
  # ephemeral environments where the docker CLI exists but no daemon does.
  if ! docker info >/dev/null 2>&1; then
    echo "→ docker CLI present but daemon unreachable; skipping docker path." >&2
    return 1
  fi
  echo "→ Starting Postgres via docker compose..." >&2
  if ! docker compose up -d db >&2; then
    return 1
  fi
  echo "→ Waiting for db to be healthy..." >&2
  local tries=0
  until docker compose exec -T db pg_isready -U "$DB_USER" -d "$DB_NAME" >/dev/null 2>&1; do
    tries=$((tries + 1))
    if [ "$tries" -gt 30 ]; then
      echo "✗ db did not become ready within 60s" >&2
      return 1
    fi
    sleep 2
  done
  DATABASE_URL="postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME"
  return 0
}

try_system_postgres() {
  if ! command -v psql >/dev/null 2>&1; then
    return 1
  fi
  # Try common cluster managers (Debian/Ubuntu) — start if not running.
  if command -v pg_lsclusters >/dev/null 2>&1; then
    local status
    status="$(pg_lsclusters -h 2>/dev/null | awk '$4=="online"{print "online"; exit}')"
    if [ "$status" != "online" ]; then
      echo "→ Starting system Postgres cluster..." >&2
      sudo pg_ctlcluster 16 main start >&2 2>/dev/null || sudo service postgresql start >&2 2>/dev/null || true
    fi
  fi
  # Ensure role + database exist. Use peer auth for postgres superuser.
  echo "→ Ensuring role '$DB_USER' and database '$DB_NAME' exist..." >&2
  sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1 || \
    sudo -u postgres psql -c "CREATE ROLE \"$DB_USER\" LOGIN PASSWORD '$DB_PASS' CREATEDB" >/dev/null
  sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1 || \
    sudo -u postgres psql -c "CREATE DATABASE \"$DB_NAME\" OWNER \"$DB_USER\"" >/dev/null
  DATABASE_URL="postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME"
  return 0
}

if try_docker_compose; then
  :
elif try_system_postgres; then
  echo "→ Using system Postgres (Docker not available)." >&2
else
  cat >&2 <<EOF
✗ Could not bring up Postgres.

Install one of:
  - Docker Desktop (recommended): https://docs.docker.com/get-docker/
  - Postgres 16:                   https://www.postgresql.org/download/

Then run: npm run db:up
EOF
  exit 1
fi

# Write .env.local for the app to pick up, unless the user already has one.
if [ ! -f ".env.local" ]; then
  cat > .env.local <<EOF
# Auto-generated by scripts/db-up.sh — feel free to edit.
DATABASE_URL=$DATABASE_URL
EOF
  echo "→ Wrote .env.local with DATABASE_URL" >&2
fi

echo "$DATABASE_URL"
